version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: pass
      POSTGRES_USER: admin
    ports: 
        - 5432:5432
  cache:
    image: redis
    restart: always
    ports: 
      - 6379:6379